##  xmod.g
LoadPackage("xmod");
Print( "running xmod01.tst\n" );
Test( "tst/manual/xmod01.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod02.tst\n" );
Test( "tst/manual/xmod02.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod03.tst\n" );
Test( "tst/manual/xmod03.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod04.tst\n" );
Test( "tst/manual/xmod04.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod05.tst\n" );
Test( "tst/manual/xmod05.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod06.tst\n" );
Test( "tst/manual/xmod06.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod07.tst\n" );
Test( "tst/manual/xmod07.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod08.tst\n" );
Test( "tst/manual/xmod08.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod09.tst\n" );
Test( "tst/manual/xmod09.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod10.tst\n" );
Test( "tst/manual/xmod10.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod11.tst\n" );
Test( "tst/manual/xmod11.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod12.tst\n" );
Test( "tst/manual/xmod12.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod13.tst\n" );
Test( "tst/manual/xmod13.tst", rec(compareFunction := "uptowhitespace") ); 
Print( "running xmod14.tst\n" );
Test( "tst/manual/xmod14.tst", rec(compareFunction := "uptowhitespace") ); 
